name: unsafe-actions

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@main
      - uses: acme/internal-action
      - uses: ./local-action
